headers: {"user-agent": "kkecher (kkecher@gmail.com)"}

database: "./data/hh.db"
areas_table: "areas"
vacancies_table: "vacancies"
streets_table: "streets"
metro_stations_table: "metro_stations"
employers_table: "employers"
vacancies_metro_stations_table: "vacancies_metro_stations"

# Debugging files
areas_file: "./data/areas.json"
vacancies_file: "./data/vacancies.json"

# clean vacancies: vacancies NOT containing undesirable pattern
# dirty vacancies (for debugging): vacancies do containing undesirable pattern
# patterns are in ‘telegram’ module
telegram_clean_vacancies_file_path: "./data/clean_vacancies/"
telegram_dirty_vacancies_file_path: "./data/dirty_vacancies/"
income_tax: 0.13
chat_id: 383837232
# token: put it in "hh_bot_token" environment variable